# Generated by Django 3.0.3 on 2020-06-11 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20200611_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresets',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 19, 4, 38, 440277)),
        ),
        migrations.AlterField(
            model_name='passwordresets',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
