# Generated by Django 3.0.3 on 2020-06-12 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20200611_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresets',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 15, 23, 24, 617818)),
        ),
    ]
