# Generated by Django 3.0.3 on 2020-06-12 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20200612_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresets',
            name='expiry',
        ),
        migrations.AddField(
            model_name='passwordresets',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 15, 27, 21, 219725)),
        ),
    ]
