# Generated by Django 3.0.3 on 2020-06-12 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20200612_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresets',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 15, 17, 58, 144317)),
        ),
    ]
