# Generated by Django 3.0.3 on 2020-06-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_auto_20200612_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresets',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
